In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import calendar 
from datetime import datetime
import pytz
import openpyxl

In [4]:
fcr_d_1_df_2022 = pd.read_excel("/Users/sandermeland/Documents/Jobb/Volte/master-kode/markets/markets-data/new_fcrd1.xlsx")
fcr_d_2_df_2022 = pd.read_excel("/Users/sandermeland/Documents/Jobb/Volte/master-kode/markets/markets-data/new_fcrd2.xlsx")
fcr_d_1_df_2023 = pd.read_excel("/Users/sandermeland/Documents/Jobb/Volte/master-kode/markets/markets-data/FCR_D-1-2023.xlsx")
fcr_d_2_df_2023 = pd.read_excel("/Users/sandermeland/Documents/Jobb/Volte/master-kode/markets/markets-data/FCR_D-2-2023.xlsx")

fcr_dfs = {"FCR_D-1_2022" : fcr_d_1_df_2022, "FCR_D-2_2022" : fcr_d_2_df_2022, "FCR_D-1_2023" : fcr_d_1_df_2023, "FCR_D-2_2023" : fcr_d_2_df_2023}

In [5]:
def preprocess_FCR(df: pd.DataFrame, area : str, start_month : int, year : int, start_day : int, end_month : int, end_day : int, start_hour : int, end_hour : int):
    """ The datasets downloaded from Statnett is quite messy and needs some preprocessing. This function removes all the columns that has price in NOK/MW as they are only 0/NaN. It also fills all the NaN values in the columns Price EUR/MW with 0.

    Args:
        df (pd.DataFrame): The dataframe to be preprocessed

    Returns:
        df: preprocessed version of the input dataframe
    """
    # drop the columns that only includes nan values
    for col in df.columns:
        if "NOK" in col:
            df = df.drop(columns=[col])
    df["FCR-D Price EUR/MW"] = df["FCR-D Price EUR/MW"].fillna(0)
    df.drop(columns= 'Hournumber', inplace=True)
    date_format = '%d.%m.%Y %H:%M:%S %z'
    
    #timezone = pytz.timezone("Europe/Oslo")    
    
    # Convert "Time(Local)" column to datetime objects
    df["Time(Local)"] = pd.to_datetime(df["Time(Local)"], format=date_format)
    
    start_datetime = pd.Timestamp(year = year, month= start_month, day = start_day, hour = 0, tz = "Europe/Oslo")
    
        
    end_datetime = pd.Timestamp(year = year, month=end_month, day = end_day, hour = 0, tz = "Europe/Oslo")
    
    # Convert "Time(Local)" column to datetime objects - this should have been done before
   # df["Time(Local)"] = pd.to_datetime(df["Time(Local)"], format=date_format)
    
    # Filter based on date range
    filtered_df = df[(df["Time(Local)"] >= start_datetime) & (df["Time(Local)"] < end_datetime)]
    
    # Filter by area
    monthly_area_df = filtered_df[filtered_df["Area"] == area]
    
    # Sort by "Time(Local)" column
    monthly_area_df = monthly_area_df.sort_values(by="Time(Local)").reset_index(drop=True)
    
    return monthly_area_df

In [8]:
updated_fcr_d_1_df = preprocess_FCR(fcr_d_1_df_2023, "NO5", year = 2023, start_month= 6, end_month= 6, start_day= 25, end_day = 27, start_hour = 0, end_hour = 24)

In [9]:
updated_fcr_d_1_df

,Time(Local),Area,FCR-N Price EUR/MW,FCR-N Volume MW,FCR-D Price EUR/MW,FCR-D Volume MW
0,2023-06-25 00:00:00+02:00,NO5,21.09,43,6.0,17
1,2023-06-25 01:00:00+02:00,NO5,21.09,38,7.0,20
2,2023-06-25 02:00:00+02:00,NO5,19.50,38,6.6,15
3,2023-06-25 03:00:00+02:00,NO5,19.50,32,6.6,14
4,2023-06-25 04:00:00+02:00,NO5,19.50,34,6.6,15
5,2023-06-25 05:00:00+02:00,NO5,19.50,34,5.0,14
6,2023-06-25 06:00:00+02:00,NO5,34.60,43,6.0,15
7,2023-06-25 07:00:00+02:00,NO5,51.38,51,8.1,23
8,2023-06-25 08:00:00+02:00,NO5,50.15,51,8.1,25
9,2023-06-25 09:00:00+02:00,NO5,49.50,33,8.1,19
10,2023-06-25 10:00:00+02:00,NO5,101.20,38,9.0,22
11,2023-06-25 11:00:00+02:00,NO5,90.10,34,8.1,18
12,2023-06-25 12:00:00+02:00,NO5,91.20,32,9.0,22
13,2023-06-25 13:00:00+02:00,NO5,91.20,31,9.0,22
14,2023-06-25 14:00:00+02:00,NO5,82.60,31,10.0,24
15,2023-06-25 15:00:00+02:00,NO5,85.70,34,7.1,18
16,2023-06-25 16:00:00+02:00,NO5,41.50,30,7.1,12
17,2023-06-25 17:00:00+02:00,NO5,42.50,52,5.0,12
18,2023-06-25 18:00:00+02:00,NO5,31.60,50,5.0,11
19,2023-06-25 19:00:00+02:00,NO5,33.74,50,5.0,11
20,2023-06-25 20:00:00+02:00,NO5,34.50,50,6.6,11
21,2023-06-25 21:00:00+02:00,NO5,34.60,54,5.0,14
22,2023-06-25 22:00:00+02:00,NO5,33.10,54,6.0,17
23,2023-06-25 23:00:00+02:00,NO5,33.74,54,6.6,14
24,2023-06-26 00:00:00+02:00,NO5,18.00,41,6.0,8
25,2023-06-26 01:00:00+02:00,NO5,28.60,49,5.0,5
26,2023-06-26 02:00:00+02:00,NO5,34.10,49,5.0,8
27,2023-06-26 03:00:00+02:00,NO5,31.00,53,5.0,8
28,2023-06-26 04:00:00+02:00,NO5,31.00,53,5.1,5
29,2023-06-26 05:00:00+02:00,NO5,43.26,53,6.0,11
30,2023-06-26 06:00:00+02:00,NO5,18.00,42,5.1,5
31,2023-06-26 07:00:00+02:00,NO5,18.50,29,6.0,8
32,2023-06-26 08:00:00+02:00,NO5,21.09,30,6.0,11
33,2023-06-26 09:00:00+02:00,NO5,18.00,28,6.0,11
34,2023-06-26 10:00:00+02:00,NO5,20.90,30,6.0,11
35,2023-06-26 11:00:00+02:00,NO5,22.50,48,6.0,8
36,2023-06-26 12:00:00+02:00,NO5,18.00,53,6.1,18
37,2023-06-26 13:00:00+02:00,NO5,47.55,58,6.0,8
38,2023-06-26 14:00:00+02:00,NO5,47.11,63,6.0,8
39,2023-06-26 15:00:00+02:00,NO5,47.28,62,6.0,11
40,2023-06-26 16:00:00+02:00,NO5,47.14,56,6.0,11
41,2023-06-26 17:00:00+02:00,NO5,20.70,43,5.1,8
42,2023-06-26 18:00:00+02:00,NO5,18.00,51,5.1,8
43,2023-06-26 19:00:00+02:00,NO5,18.00,51,5.0,5
44,2023-06-26 20:00:00+02:00,NO5,18.00,53,5.0,5
45,2023-06-26 21:00:00+02:00,NO5,18.00,41,5.0,8
46,2023-06-26 22:00:00+02:00,NO5,21.00,48,5.1,8
47,2023-06-26 23:00:00+02:00,NO5,20.80,50,5.1,5

# There is no missing values in NO5 in 2023

In [38]:
def get_date_related_fcr_df(dict : dict, market : str, area : str, start_month : int, year : int, start_day : int, end_month : int, end_day : int):
    """ function to filter the data by area and month

    Args:
        df (pd.DataFrame): dataframe to filter - should be for one given market in one specific year
        area (str): wanted area - chosen from [NO1, NO2, NO3, NO4, NO5]
        month (int): wanted month - chosen from [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    """
    df = dict[market]
    #date_format = '%Y-%m-%d %H:%M:%S%z'
    
    #timezone = pytz.timezone("Europe/Oslo")    
    start_datetime = pd.Timestamp(year = year, month= start_month, day = start_day, hour = 0, tz = "Europe/Oslo")
    
        
    end_datetime = pd.Timestamp(year = year, month=end_month, day = end_day, hour = 0, tz = "Europe/Oslo")
    
    # Convert "Time(Local)" column to datetime objects - this should have been done before
   # df["Time(Local)"] = pd.to_datetime(df["Time(Local)"], format=date_format)
    
    # Filter based on date range
    filtered_df = df[(df["Time(Local)"] >= start_datetime) & (df["Time(Local)"] < end_datetime)]
    
    # Filter by area
    monthly_area_df = filtered_df[filtered_df["Area"] == area]
    
    # Sort by "Time(Local)" column
    monthly_area_df = monthly_area_df.sort_values(by="Time(Local)").reset_index(drop=True)
    
    return monthly_area_df

In [39]:
get_date_related_fcr_df(fcr_dfs, "FCR_D-1_2023", area= "NO5", start_day=26, start_month= 6, end_day= 27, end_month= 6, year= 2023)

,Time(Local),Area,FCR-N Price EUR/MW,FCR-N Volume MW,FCR-D Price EUR/MW,FCR-D Volume MW
0,2023-06-26 00:00:00+02:00,NO5,18.00,41,6.0,8
1,2023-06-26 01:00:00+02:00,NO5,28.60,49,5.0,5
2,2023-06-26 02:00:00+02:00,NO5,34.10,49,5.0,8
3,2023-06-26 03:00:00+02:00,NO5,31.00,53,5.0,8
4,2023-06-26 04:00:00+02:00,NO5,31.00,53,5.1,5
5,2023-06-26 05:00:00+02:00,NO5,43.26,53,6.0,11
6,2023-06-26 06:00:00+02:00,NO5,18.00,42,5.1,5
7,2023-06-26 07:00:00+02:00,NO5,18.50,29,6.0,8
8,2023-06-26 08:00:00+02:00,NO5,21.09,30,6.0,11
9,2023-06-26 09:00:00+02:00,NO5,18.00,28,6.0,11
10,2023-06-26 10:00:00+02:00,NO5,20.90,30,6.0,11
11,2023-06-26 11:00:00+02:00,NO5,22.50,48,6.0,8
12,2023-06-26 12:00:00+02:00,NO5,18.00,53,6.1,18
13,2023-06-26 13:00:00+02:00,NO5,47.55,58,6.0,8
14,2023-06-26 14:00:00+02:00,NO5,47.11,63,6.0,8
15,2023-06-26 15:00:00+02:00,NO5,47.28,62,6.0,11
16,2023-06-26 16:00:00+02:00,NO5,47.14,56,6.0,11
17,2023-06-26 17:00:00+02:00,NO5,20.70,43,5.1,8
18,2023-06-26 18:00:00+02:00,NO5,18.00,51,5.1,8
19,2023-06-26 19:00:00+02:00,NO5,18.00,51,5.0,5
20,2023-06-26 20:00:00+02:00,NO5,18.00,53,5.0,5
21,2023-06-26 21:00:00+02:00,NO5,18.00,41,5.0,8
22,2023-06-26 22:00:00+02:00,NO5,21.00,48,5.1,8
23,2023-06-26 23:00:00+02:00,NO5,20.80,50,5.1,5